## Introduction
In this assignment, I chose to explore the electric vehicle population for the state of Washington (see the link below) due. I have an interest in the evolving electric car market, so I thought this would be an interesting dataset to explore. The dataset shows a subset (n=1000) of the full-electric vehicles and plug-in hybrids that are currently registered in Washington State.

## Data Exploration

In [3]:
#Data Import and exploration
import pandas as pd
electric_cars = pd.read_csv("https://www.pro-football-reference.com/years/2024/#team_stats")
print("Dataframe dimensions (rows, columns):",electric_cars.shape, "\n")

print(electric_cars.info(),"\n")

print("Descriptive Statistics of each Column:\n",electric_cars.describe(),"\n")

print("Missing Values in each Column:\n", electric_cars.isnull().sum())

Dataframe dimensions (rows, columns): (1000, 17)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   vin_1_10              1000 non-null   object
 1   county                999 non-null    object
 2   city                  999 non-null    object
 3   state                 1000 non-null   object
 4   zip_code              999 non-null    float64
 5   model_year            1000 non-null   int64
 6   make                  1000 non-null   object
 7   model                 1000 non-null   object
 8   ev_type               1000 non-null   object
 9   cafv_type             1000 non-null   object
 10  electric_range        1000 non-null   int64
 11  base_msrp             1000 non-null   int64
 12  legislative_district  996 non-null    float64
 13  dol_vehicle_id        1000 non-null   int64
 14  geocoded_column       999 non-null    object
 15  electric_utility      999 non-null    object
 16  _2020_census_tract    999 non-null    float64
dtypes: float64(3), int64(4), object(10)
memory usage: 132.9+ KB
None

Descriptive Statistics of each Column:
            zip_code   model_year  electric_range    base_msrp  \
count    999.000000  1000.000000     1000.000000    1000.0000
mean   98226.946947  2020.726000       73.510000    1034.0000
std     1532.915030     3.454107       96.300133    9416.4762
min    53588.000000  2008.000000        0.000000       0.0000
25%    98037.500000  2018.000000        0.000000       0.0000
50%    98155.000000  2022.000000       25.000000       0.0000
75%    98413.500000  2024.000000      125.250000       0.0000
max    99362.000000  2026.000000      330.000000  184400.0000

       legislative_district  dol_vehicle_id  _2020_census_tract
count            996.000000    1.000000e+03        9.990000e+02
mean              27.155622    2.372954e+08        5.296203e+10
std               14.740805    8.213674e+07        1.894276e+09
min                1.000000    1.956790e+06        6.019004e+09
25%               15.000000    1.994707e+08        5.303302e+10
50%               27.000000    2.552460e+08        5.303303e+10
75%               40.000000    2.760781e+08        5.306105e+10
max               49.000000    4.784520e+08        5.511100e+10

Missing Values in each Column:
 vin_1_10                0
county                  1
city                    1
state                   0
zip_code                1
model_year              0
make                    0
model                   0
ev_type                 0
cafv_type               0
electric_range          0
base_msrp               0
legislative_district    4
dol_vehicle_id          0
geocoded_column         1
electric_utility        1
_2020_census_tract      1
dtype: int64

## Data Wrangling

In [4]:
# 1. Modify multiple column names.
#Simplified two column names
print("1.Modify multiple column names.\n")
electric_cars.rename(columns={"vin_1_10":"VIN", "dol_vehicle_id": "id", "electric_utility": "utility"}, inplace=True)
print(electric_cars.info(),"\n") 

# 2. Look at the structure of your data – are any variables improperly coded? Such as strings or characters? 
#Changed generic object type to string
print("2. Redefine improperly coded variables \n")
electric_cars['VIN'] = electric_cars['VIN'].astype('string')
electric_cars['county'] = electric_cars['county'].astype('string')
electric_cars['city'] = electric_cars['city'].astype('string')
electric_cars['state'] = electric_cars['state'].astype('string')
electric_cars['make'] = electric_cars['make'].astype('string')
electric_cars['model'] = electric_cars['model'].astype('string')
electric_cars['ev_type'] = electric_cars['ev_type'].astype('string')
electric_cars['cafv_type'] = electric_cars['cafv_type'].astype('string')
electric_cars['geocoded_column'] = electric_cars['geocoded_column'].astype('string')
electric_cars['utility'] = electric_cars['utility'].astype('string')
print(electric_cars.info(), "\n") 

# 3. Fix missing and invalid values in data.
#dropped rows with missing data
print("3. Fix missing and invalid values in data. \n")
electric_cars.dropna(inplace = True)
print(electric_cars.shape,"\n")

# 4. Create new columns based on existing columns or calculations.
#created two new columns
print("4. Create new columns based on existing columns or calculations.\n")
electric_cars['range_comp_to_mean'] = electric_cars['electric_range']/electric_cars['electric_range'].mean()
electric_cars['is_tesla_or_audi'] = electric_cars['make'].apply(lambda x: 1 if x == "TESLA" or x == "AUDI" else 0)
print(electric_cars.columns,"\n")

# 5. Drop column(s) from your dataset.
#dropped base_msrp since most values were $0
print("5. Drop column(s) from your dataset.\n")
electric_cars.drop(columns=['base_msrp'],inplace = True)
print(electric_cars.columns, "\n")

# 6. Drop a row(s) from your dataset.
#Dropped the first 3 rows
print("6. Drop rows from your dataset.\n")
electric_cars.drop([0,1,2], inplace = True)
print(electric_cars.shape,"\n")

# 7. Sort your data based on multiple variables.
#Sorted data based on zip code and electric range
print("7. Sort your data based on multiple variables.\n")
sorted = electric_cars.sort_values(['zip_code','electric_range'])
print(sorted.head())
print("\n")

# 8. Filter your data based on some condition.
#filtered rows based on whether they had useful (non-zero) information regarding range
print("8. Filter your data based on some condition. \n")
electric_cars_filtered = electric_cars[electric_cars['electric_range'] > 0]
print(electric_cars_filtered.shape)
print("\n")

# 9. Convert all the string values to upper or lower cases in one column.
#Converted strings in the "make" column to lower case
print("9. Convert all the string values to upper or lower cases in one column.\n")
electric_cars_filtered.loc[:,'make'] = electric_cars_filtered['make'].str.lower()
print(electric_cars_filtered['make'])
print("\n")

# 10. Check whether numeric values are present in a given column of your dataframe.
print("10. Check whether numeric values are present in a given column of your dataframe. \n")
print(electric_cars_filtered.dtypes)
print("\n")

# 11. Group your dataset by one column, and get the mean, min, and max values by group.
#Grouped model year and examined the mean, min, and mix values of the electric range
print("11.Group your dataset by one column, and get the mean, min, and max values by group.\n ")
print(electric_cars_filtered.groupby('model_year')['electric_range'].agg(['mean', 'min', 'max']))

1.Modify multiple column names.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   VIN                   1000 non-null   object
 1   county                999 non-null    object
 2   city                  999 non-null    object
 3   state                 1000 non-null   object
 4   zip_code              999 non-null    float64
 5   model_year            1000 non-null   int64
 6   make                  1000 non-null   object
 7   model                 1000 non-null   object
 8   ev_type               1000 non-null   object
 9   cafv_type             1000 non-null   object
 10  electric_range        1000 non-null   int64
 11  base_msrp             1000 non-null   int64
 12  legislative_district  996 non-null    float64
 13  id                    1000 non-null   int64
 14  geocoded_column       999 non-null    object
 15  utility               999 non-null    object
 16  _2020_census_tract    999 non-null    float64
dtypes: float64(3), int64(4), object(10)
memory usage: 132.9+ KB
None

2. Redefine improperly coded variables

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   VIN                   1000 non-null   string
 1   county                999 non-null    string
 2   city                  999 non-null    string
 3   state                 1000 non-null   string
 4   zip_code              999 non-null    float64
 5   model_year            1000 non-null   int64
 6   make                  1000 non-null   string
 7   model                 1000 non-null   string
 8   ev_type               1000 non-null   string
 9   cafv_type             1000 non-null   string
 10  electric_range        1000 non-null   int64
 11  base_msrp             1000 non-null   int64
 12  legislative_district  996 non-null    float64
 13  id                    1000 non-null   int64
 14  geocoded_column       999 non-null    string
 15  utility               999 non-null    string
 16  _2020_census_tract    999 non-null    float64
dtypes: float64(3), int64(4), string(10)
memory usage: 132.9 KB
None

3. Fix missing and invalid values in data.

(996, 17)

4. Create new columns based on existing columns or calculations.

Index(['VIN', 'county', 'city', 'state', 'zip_code', 'model_year', 'make',
       'model', 'ev_type', 'cafv_type', 'electric_range', 'base_msrp',
       'legislative_district', 'id', 'geocoded_column', 'utility',
       '_2020_census_tract', 'range_comp_to_mean', 'is_tesla_or_audi'],
      dtype='object')

5. Drop column(s) from your dataset.

Index(['VIN', 'county', 'city', 'state', 'zip_code', 'model_year', 'make',
       'model', 'ev_type', 'cafv_type', 'electric_range',
       'legislative_district', 'id', 'geocoded_column', 'utility',
       '_2020_census_tract', 'range_comp_to_mean', 'is_tesla_or_audi'],
      dtype='object')

6. Drop rows from your dataset.

(993, 18)

7. Sort your data based on multiple variables.

            VIN county         city state  zip_code  model_year       make  \
741  5YJ3E1EB7S   King  Federal Way    WA   98001.0        2025      TESLA
916  7G2CEHED7S   King       Algona    WA   98001.0        2025      TESLA
929  3GNKDCRJ1R   King       Auburn    WA   98001.0        2024  CHEVROLET
955  5YJ3E1EC9N   King  Federal Way    WA   98001.0        2022      TESLA
533  1G1FZ6S05L   King       Auburn    WA   98001.0        2020  CHEVROLET

          model                         ev_type  \
741     MODEL 3  Battery Electric Vehicle (BEV)
916  CYBERTRUCK  Battery Electric Vehicle (BEV)
929      BLAZER  Battery Electric Vehicle (BEV)
955     MODEL 3  Battery Electric Vehicle (BEV)
533     BOLT EV  Battery Electric Vehicle (BEV)

                                             cafv_type  electric_range  \
741  Eligibility unknown as battery range has not b...               0
916  Eligibility unknown as battery range has not b...               0
929  Eligibility unknown as battery range has not b...               0
955  Eligibility unknown as battery range has not b...               0
533            Clean Alternative Fuel Vehicle Eligible             259

     legislative_district         id             geocoded_column  \
741                  30.0  278669191  POINT (-122.23035 47.3074)
916                  30.0  284100036  POINT (-122.23035 47.3074)
929                  47.0  262396543  POINT (-122.23035 47.3074)
955                  30.0  204864481  POINT (-122.23035 47.3074)
533                  30.0  277629915  POINT (-122.23035 47.3074)

                                           utility  _2020_census_tract  \
741  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)        5.303303e+10
916  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)        5.303303e+10
929  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)        5.303303e+10
955  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)        5.303303e+10
533  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)        5.303303e+10

     range_comp_to_mean  is_tesla_or_audi
741            0.000000                 1
916            0.000000                 1
929            0.000000                 0
955            0.000000                 1
533            3.535255                 0


8. Filter your data based on some condition.

(577, 18)


9. Convert all the string values to upper or lower cases in one column.

3         audi
5          kia
6       nissan
7          kia
8      hyundai
        ...
991      tesla
994        bmw
995      tesla
996      mazda
998     nissan
Name: make, Length: 577, dtype: string


10. Check whether numeric values are present in a given column of your dataframe.

VIN                      string
county                   string
city                     string
state                    string
zip_code                float64
model_year                int64
make                     string
model                    string
ev_type                  string
cafv_type                string
electric_range            int64
legislative_district    float64
id                        int64
geocoded_column          string
utility                  string
_2020_census_tract      float64
range_comp_to_mean      float64
is_tesla_or_audi          int64
dtype: object


11.Group your dataset by one column, and get the mean, min, and max values by group.

                  mean  min  max
model_year
2008        220.000000  220  220
2011         73.000000   73   73
2012         60.333333   35   73
2013         80.391304    6  208
2014         83.285714   14  208
2015        108.911765   19  208
2016        101.975000   14  210
2017        121.377778   12  238
2018        164.171717    8  249
2019        190.328947   25  289
2020        259.242857   18  330
2021         68.937500   17  233
2022         28.111111   18   42
2023         31.580645   21   42
2024         31.489362   21   48
2025         35.111111   21   58
2026         38.000000   38   38

C:\Users\kjr50\AppData\Local\Temp\ipykernel_19340\1898569400.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  electric_cars_filtered.loc[:,'make'] = electric_cars_filtered['make'].str.lower()

## Conclusions
The data was grouped by model year, then the electric range was summarized via mean, max, and min values. The results were surprising in that the mean range varied considerably over time rather than improving. This unlikely a true reflection of reality, but rather is due to limitations of the data set. Many of of the electric range values are suspiciously low, so I suspect that some of the data in the electric_range column is actually the miles per gallon equivalent (MPGe) rather than range. An attribute that is inconsistently defined is challenging to use for analysis and would likely lead to a "garbage in, garbage out" result. Ultimately, I would seek out an alternative data set if I were to further analyze the electric vehicle market in Washington state.